<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "css_ce"
 *
 * Auto generated by Extension Builder 2014-03-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CSS for content elements',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Ingo Reuter',
	'author_email' => 'mail@ingoreuter.de',
	'author_company' => 'Ingo Reuter',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => 'uploads/tx_cssce/backgroundimages',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.9.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>